### ISSUE TITLE
Change toolbar name

### ISSUE THREAD

**Issue by xmha97** [mhdzli/mahour#2]
سلام
امکان داره اسم تولبار رو از «ماهور» به "Mahour" تغییر بدید؟
![Thunderbird](https://user-images.githubusercontent.com/23485114/108491276-f3841280-72b8-11eb-86ba-9f6881be75a0.png)

**Comment by mhdzli** [comment]
@xmha97 
فارسی بودنش چه مشکلی ایجاد می‌کنه؟

**Comment by xmha97** [comment]
مشکلی رو که ایجاد نمی‌کنه صرفا بر اساس سلیقه گفتم
در هر صورت به نظرم زیاد هم مهم نیست و من این ایشو رو می‌بندم

**Comment by mhdzli** [comment]
@xmha97 
از اونجا که کاربرد خاصی نداره و فقط برای شروع به عنوان معرفی و راهنما استفاده شد، تو نسخه‌های بعدی احتمالا حذف می‌شه. فعلا دارم روی اضافه کردن تاریخ فارسی به تسک منیجر وقت می‌ذارم

**Comment by xmha97** [comment]
ممنون از شما، به نظر منم حذف شه بهتره
