### ISSUE TITLE
Mahour is incompatible with Thunderbird 97.0

### ISSUE THREAD

**Issue by xmha97** [mhdzli/mahour#4]
![image](https://user-images.githubusercontent.com/23485114/151905299-43a465b6-e917-4698-988f-6b7de0f6304c.png)

**Comment by xmha97** [comment]
ببخشید امکان داره تاندربرد بتا رو نصب کنید و این مشکل رو پیگیری کنید؟

**Comment by xmha97** [comment]
![image](https://user-images.githubusercontent.com/23485114/152953524-b9518d1b-ae9f-4bb1-a127-0c0a8acb06a8.png)

**Comment by mhdzli** [comment]
در اولین فرصت چک میکنم ببینم مشکل از کجاست.
باید ببینم تغییرات نسخه ۹۲ چی بوده و احتمالا داکیومنتهای مربوط به افزونه‌های تاندربرد رو مرور کنم که زمانبر هست.

**Comment by mhdzli** [comment]
> ببخشید امکان داره تاندربرد بتا رو نصب کنید و این مشکل رو پیگیری کنید؟

چک کردم و با تاندربرد نسخه بالاتر هم در حالتی که دستی نصب می‌کنم مشکلی نداره اما سایت گالری تاندربرد اجازه نمی‌ده محدودیت ماکزیمم ورژن رو بردارم فعلا تو کانال توسعه دهنده‌ها سوال کردم ببینم آیا می‌تونم راهی پیدا کنم یا نه.

**Comment by mhdzli** [comment]
done in 312e5f64512d9ac25452cc5b528115987a9a58bd
