### ISSUE TITLE
new thunderbird 102 compatibality

### ISSUE THREAD

**Issue by rezad1393** [mhdzli/mahour#6]
سلام
can you test the with new beta thunderbird released?
and if it is compatible can you increase the version in the thunderbird addon websites so that users can install it normally?

**Comment by mhdzli** [comment]
done in 312e5f64512d9ac25452cc5b528115987a9a58bd

**Comment by mhdzli** [comment]
It's updated on thunderbird gallery too

@rezad1393

**Comment by rezad1393** [comment]
تشکر
