### ISSUE TITLE
 Mahour is incompatible with Thunderbird 115

### ISSUE THREAD

**Issue by xmha97** [mhdzli/mahour#8]
Hi, Mahour is incompatible with Thunderbird 115

![image](https://github.com/mhdzli/mahour/assets/23485114/6d6ad361-572e-4ca7-986c-e41954677831)

**Comment by pouriap** [comment]
سلام
کلا custom column در نسخه جدید وجود نداره؟
اگر امکان سازگار کردن با نسخه جدید وجود نداره برگردم به نسخه قبلی چون تاریخ میلادی قابل استفاده نیست.

**Comment by mhdzli** [comment]
@pouriap 
آخرین نسخه‌ای که custom column v رو پشتیبانی می‌کنه فعلا نسخه ۱۱۰ هست.

**Comment by xmha97** [comment]
> @pouriap 
> آخرین نسخه‌ای که custom column v رو پشتیبانی می‌کنه فعلا نسخه ۱۱۰ هست.

چقدر بد :(
ممنون از پاسخگویی‌تون

**Comment by pouriap** [comment]
> @pouriap آخرین نسخه‌ای که custom column v رو پشتیبانی می‌کنه فعلا نسخه ۱۱۰ هست.

همون بلایی که سر فایرفاکس اوردن و به افتضاح کشوندنش رو معلومه که دارن سر تاندربرد هم میارن. دیگه حتی ساده ترین چیزها هم قابلیت شخصی سازی نداره. API اکستنشن ها هر روز ضعیف تر و خنده دارتر از روز قبل. فقط پسرفت.

**Comment by mhdzli** [comment]
@pouriap 
با چند نفر از توسعه دهنده‌ها که صحبت کردم گفتن که دارن پیگیری می‌کنن که امکان اضافه شدن ستون توی نسخه‌های جدید هم اضافه بشه.
من ماکزیمم ورژن رو توی گالری تاندربرد فعلا روی ۱۱۰ گذاشتم که اگر کسی خواست بتونه روی این نسخه ازش اضافه کنه و هر زمان که این امکان تو نسخه‌های جدید هم به وجود آمد به روزش می‌کنم.
یه صحبتی هم کردیم که امکان انتخاب تقویم فارسی هم به صورت یه گزینه تو تنظیمات کل پروژه اضافه بشه که اگر این اتفاق بیفته خیلی خوبه و توی تسک منیجر هم امکان استفاده از تقویم فارسی رو خواهیم داشت.

**Comment by pouriap** [comment]
ممنون از پیگیریتون.

**Comment by xmha97** [comment]
> @pouriap با چند نفر از توسعه دهنده‌ها که صحبت کردم گفتن که دارن پیگیری می‌کنن که امکان اضافه شدن ستون توی نسخه‌های جدید هم اضافه بشه. من ماکزیمم ورژن رو توی گالری تاندربرد فعلا روی ۱۱۰ گذاشتم که اگر کسی خواست بتونه روی این نسخه ازش اضافه کنه و هر زمان که این امکان تو نسخه‌های جدید هم به وجود آمد به روزش می‌کنم. یه صحبتی هم کردیم که امکان انتخاب تقویم فارسی هم به صورت یه گزینه تو تنظیمات کل پروژه اضافه بشه که اگر این اتفاق بیفته خیلی خوبه و توی تسک منیجر هم امکان استفاده از تقویم فارسی رو خواهیم داشت.

ممنون از پیگیری‌تون

**Comment by mhdzli** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1817682

**Comment by mhdzli** [comment]
There is some development in adding an API. Here are some links if anyone is interested:
https://bugzilla.mozilla.org/show_bug.cgi?id=1615801
https://phabricator.services.mozilla.com/D196693
https://github.com/Standard8/thunderbird-conversations/blob/95cace58e1623e8aa89c817d5d8166dae2dc7ad9/addon/uiHandler.js#L19-L43
https://github.com/lkosson/full-address-column/issues/11#issuecomment-1024954835

Unfortunately I don't have enough free time to read and see if it's possible to rewrite the code for newer versions of Thunderbird right now.

**Comment by AmanRathoreP** [comment]
Recently, I had published an addon releated to displaying relative dates in Thunderbird. You might like to have a look at it as it does almost the same thing, but it displays relative dates instead of Persian dates. However, one can update `get_addon_provided_relative_date_time` function in [src/backend/custom_column.js](https://github.com/AmanRathoreP/Mozilla-Thunderbird-Date-Time-Formatter/blob/0379fbcdb106656f8b72889f2824122ebc6fe538/src/backend/custom_column.js#L34) to get desired functionality
> * `get_addon_provided_relative_date_time()` takes message instance as input and returns a string
> * Sorting functionality is not available in the created column.

[My addon](https://github.com/AmanRathoreP/Mozilla-Thunderbird-Date-Time-Formatter)

**Comment by mhdzli** [comment]
the commit 0d30be3 solved the issue...

**Comment by mhdzli** [comment]
the commit 0d30be3 solved the issue...

**Comment by mhdzli** [comment]
@xmha97 
@pouriap 
@AmanRathoreP 
@arai-a 

Thunderbird 115.10 - 128.*  are now supported in [mahoor version 1.2.1](https://github.com/mhdzli/mahoor/releases/tag/v1.2.1)

mahoor 1.2.0 is verified in [tb add-on gallery]( https://addons.thunderbird.net/en-US/thunderbird/addon/mahoor-iranian-date/) which supports tb v 115.10-127.*

**Comment by pouriap** [comment]
Awesome!
Works great with 115.12
