### ISSUE TITLE
make it compatible with latest versions of thunderbird   (current 115)

### ISSUE THREAD

**Issue by faridcher** [mhdzli/mahour#9]

**Comment by mhdzli** [comment]
It has been discussed in #8

**Comment by mhdzli** [comment]
@faridcher 
Thunderbird 115.10 - 128.*  are supported in mahoor version 1.2.1
mahoor 1.2.0 is verified in tb add-on gallery which supports tb v 115.10-127.*
https://addons.thunderbird.net/en-US/thunderbird/addon/mahoor-iranian-date/
